# Setup
title:               Чернетки та чорнила
tagline:             'Марина Зайцева'
description:         'Вірші, замальовки та проза. Пише <a href="https://www.instagram.com/marin_k_a/">Марина Зайцева</a>.'
url:                 https://ink.marin-k-a.com
baseurl:             ''
paginate:            5
paginate_path:       "/page:num/"
permalink:           pretty

# About/contact
author:
  name:              Марина Зайцева
  url:               https://www.instagram.com/marin_k_a/
  email:             mz.zaytseva@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: #UA-XXXX-Y
